Majored/rs-async-zip

- src/lib.rs
- src/read/mod.rs
As well as `Compression` which is a field of `ZipEntry`. Makes debugging easier by not having to call all the getter methods and print their return values one by one.
> Implement Debug for ZipEntry

- Cargo.toml
- src/error.rs
For better interop. The impls (as well as the existing `From<io::Error>` impl) are derived via the [`thiserror`](https://docs.rs/thiserror) crate, and the existing `description` method is reimplemented in terms of `Display` to avoid code duplication.
> Implement Display and Error for ZipError

- examples/actix_multipart/Cargo.toml
- examples/actix_multipart/README.md
- examples/actix_multipart/src/main.rs
Adds an example of using the library to write a Multipart request from Actix directly to a compressed archive.
> Adding actix multipart example

- src/spec/date.rs
Allows to process archives with zeroed/broken values in `header.mod_date` and `header.mod_time` without panicking.
> Return chrono::MIN_DATETIME on invalid date/time in zip header

- src/write/entry_whole.rs
- src/write/mod.rs
ISSUE: currently this library for unix/linux zipping assign 0-based permissions 0x000, which does not allow to open files after unzip (unless manually permissions changed). 
This MR adds possibility to set the the Unix permissions for the all zipped files with selected value ex. 0x755
Usage:
`
let entry_options = EntryOptions::new(name.into(), Compression::Deflate)
.unix_permissions(0o755);
`
It is initial version as pre-solution for #14 - just instead of preventing file permissions it allows to set them. 
Similar solution is applied in sync version of Rust zip library: https://github.com/zip-rs/zip
> Add possibility to select unix permissions for compressed files

- src/read/seek.rs
Example zip with max comment size 0xFFFF:
[max_comment.zip](https://github.com/Majored/rs-async-zip/files/9006074/max_comment.zip)
This previously failed to read because the start read range wasn't long enough.
> With a max length EOCDH comment the EOCDH signature could start at end-(0xffff+22)

- src/error.rs
- src/read/fs.rs
- src/read/mem.rs
- src/read/mod.rs
- src/read/seek.rs
- src/read/stream.rs
- src/read/sync.rs
- src/tests/mod.rs
This is sort of a continuation of my previous PR: #26.
As me and @mobad [discussed in the PR](https://github.com/Majored/rs-async-zip/pull/26#issuecomment-1172969788), all the decoding algorithms **rs-async-zip** uses happens to be self-terminating, which means we don't really need the `AsyncDelimiterReader` to detect the signature of *Data descriptor*.
Those changes are a little aggressive: 
- Removed `LocalReader` and made `Stored` wrap a `Take<BufReader<R>>` instead of `Take<R>` 
- This way I can unwrap the `BufReader` from all variants without hard specializing for the `Stored` case.
- Move *Data Descriptor* check to `poll_read`
- Change all readers to use `ZipEntryReader::from_raw`
- Take away `AsyncDelimiterReader` for *Data Descriptor* (only for *Data Descriptor*, because it still …
> Refactor - Remove AsyncDelimiterReader use for Stream zip reading

- src/read/mod.rs
Firstly, thanks @Majored for awesome work with this library!
I noticed that the `copy_to_end_crc` function tends to panic when underlying tokio process returns an error. Since this is breaking my application, here's one-liner fix for that.
> Handle the panic when copying the buffer

- src/tests/mod.rs
- src/write/entry_stream.rs
- src/write/entry_whole.rs
- src/write/mod.rs
I have a use case where I need to create ZIP files that are byte-identical when fed the same files. That's not currently possible with this library since the modification time on entries is always set from `Utc::now`.
This PR adds a new builder method to `EntryOptions` for setting a specific time. The method is named `last_modified` to match the corresponding getter on `ZipEntry`.
Let me know if you have any concerns or would like anything adjusted.
> Allow entry modification time to be set explicitly

- Cargo.toml
- examples/file_extraction.rs
This one is written as a [Cargo Example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) instead of a separate crate like the other examples. This way, the examples are automatically linked with the current branch instead of the main branch of the git repo. And because `cargo test` also compiles them by default, they are ensured to be up to date with the crate's public API. But, of course, if you prefer separate crates, I'll rewrite it.
> Add an example demonstrating how to safely extract ZIP files

- src/spec/date.rs
The current code always sets hour to 0
> fix bug in hour conversion of modified time

- Cargo.toml
This also removes a dependency on time 0.1.x which has a open RUSTSEC advisory.
> Remove unused features from time.

- src/entry/builder.rs
- src/entry/level.rs
- src/entry/mod.rs
- src/read/seek.rs
- src/read/stream.rs
- src/write/entry_whole.rs
This has a copy of the `async_compression::Level` enum so it can be updated without breaking the public api.
> Make it possible to set the compression level used.

- src/entry/mod.rs
- src/error.rs
- src/file/builder.rs
- src/file/mod.rs
- src/lib.rs
- src/read/io/locator.rs
- src/read/mem.rs
- src/read/mod.rs
- src/read/seek.rs
- src/spec/date.rs
- src/utils.rs
Ive been working on querying information from a ZIP archive over HTTP with the use of range requests. To be able to do that correctly I needed access to the position of an entry in the zip archive as well as access to the underlying reader.
It look like the project is going through some major refactor which causes som errors as well. I did my best to fix any issues (like signatures no longer being read) as well as some deprecation warnings.
With these changes Im able to use the current `main` branch to query and extract zip archives.
Let me know what you think! Im currently using my fork but Id much rather get this merged!
> feat: fix issues and enable querying file position

- src/spec/compression.rs
- src/write/io/offset.rs
- src/write/mod.rs
The implementation defined levels was made impossible to access directly, I am not sure if you want that specifically since you seen to go a lot up against the draft standard.
Access of the inner writer allows things like swapping out a vec or similar.
> Add specific level back and make it possible to access the inner writer.

- src/read/seek.rs
This PR makes it possible to clone a ZipFileReader (if the underlying reader can also be cloned)
> Derive Clone for ZipFileReader

- src/entry/mod.rs
- src/read/fs.rs
- src/read/io/compressed.rs
- src/read/io/entry.rs
- src/read/io/owned.rs
- src/read/mem.rs
- src/read/seek.rs
This PR fixes https://github.com/Majored/rs-async-zip/issues/54
This fix is implemented in a way where it shouldn't have an impact on the number of reads or seeks made to the underlying reader (vs the current code).
(It does this by sharing a `BufReader` between the `CompressedReader` and the code that skips the local file header + trailing data. Since the LFH + trailing data is usually significantly smaller than the buffer size, it shouldn't result in additional reads most of the time. See the issue linked above for more details)
> Fix bug in file decompression

- src/read/seek.rs
This PR adds a method that constructs a ZIP reader from a seekable source and zip file information derived from that source.
This can be used to avoid parsing the same zip file several times.
See the included comment and doctest for more details.
> Add a `from_parts` method for seek::ZipFileReader

- src/entry/builder.rs
- src/entry/mod.rs
- src/read/fs.rs
- src/read/io/combined_record.rs
- src/read/io/compressed.rs
- src/read/io/entry.rs
- src/read/io/locator.rs
- src/read/io/mod.rs
- src/read/mod.rs
- src/spec/consts.rs
- src/spec/header.rs
- src/spec/mod.rs
- src/spec/parse.rs
- src/spec/version.rs
- src/tests/read/compression/mod.rs
- src/tests/spec/date.rs
- src/write/compressed_writer.rs
- src/write/entry_whole.rs
Find the Zip64 End Of Central Directory Locator immediately instead of doing a second seek.
Deleted the unnecessary locate record by signature function, effectively un-generalizing it.
Merge after PR #72 . Fixes Issue #70
> #70: Find EOCDL directly

- Cargo.toml
- LICENSE
- src/entry/builder.rs
- src/error.rs
- src/read/mod.rs
- src/spec/consts.rs
- src/spec/parse.rs
- src/tests/read/zip64/mod.rs
- src/tests/write/mod.rs
- src/tests/write/zip64/mod.rs
- src/write/entry_stream.rs
- src/write/entry_whole.rs
- src/write/mod.rs
Zip64 Write support, with many caveats.
The main problem is, of course, that the Zip format is not strictly defined and also doesn't seem to support non-seekable writing all that well. These problems were present previously, too, but adding a reference test against another library just made them more visible.
* uncompressed_size and compressed_size in the Local File Header is either u32::MAX or 0, respectively for Zip64 mode and non-Zip64 mode. In the Zip64 Extra Field the sizes are also set to 0.
* This means any readers which defer to the Local File Header will either read too many bytes or read none.
* Our non-seekable reader will have to fall back to scanning until the next local file header.
* The crc is 0 in the Local File Header. Implementations that depend on the local file …
> Zip64 Write

- src/read/stream.rs
This is helpful, because the zip file reader does not necessarily consume the stream fully. For example, if we reach the end of the zip file contents, but the stream isn't complete, it can be helpful to be able to get the reader back to continue taking input. Even the reader implementation as is does not necessarily read the metadata at the end of the zipfile after the final file entry.
> Add an into_inner() method on stream ZipFileReader

- Cargo.toml
- examples/actix_multipart.rs
- examples/cli_compress.rs
- examples/file_extraction.rs
- src/entry/mod.rs
- src/read/fs.rs
- src/read/io/compressed.rs
- src/read/io/entry.rs
- src/read/io/hashed.rs
- src/read/io/locator.rs
- src/read/io/mod.rs
- src/read/io/owned.rs
- src/read/mem.rs
- src/read/mod.rs
- src/read/seek.rs
- src/read/stream.rs
- src/spec/parse.rs
- src/tests/read/compression/mod.rs
- src/tests/read/locator/mod.rs
- src/tests/read/zip64/mod.rs
- src/tests/write/mod.rs
- src/tests/write/offset/mod.rs
- src/tests/write/zip64/mod.rs
- src/utils.rs
- src/write/compressed_writer.rs
- src/write/entry_stream.rs
- src/write/entry_whole.rs
- src/write/io/offset.rs
- src/write/mod.rs
- tests/common/mod.rs
Addresses #17.
This does not attempt to add the feature-gated `tokio` module that the issue postulated. Using the `tokio_util::compat`-provided traits directly seems to work well (at least for me), so it is unclear to me if a special runtime-specific set of APIs is really warranted. But if you consider that to be necessary for seamless updates downstream, then it should be easy to add that in on top of this work. 🙂 
The 'fs' feature now enables the 'tokio' dependency implicitly. Therefore, I would suggest renaming the feature to 'tokio-fs' and perhaps renaming the `async_zip::read::fs` module to `async_zip::read::tokio_fs`.
> Decouple this package from tokio by using the I/O traits from futures-util

- Cargo.toml
- src/lib.rs
It will show on docs.rs which features are required for the function/type to be available.
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
> Document features on docs.rs

- src/base/read/io/combined_record.rs
- src/base/read/mod.rs
- tests/decompress_test.rs
When reading an empty ZIP-Archive,  `async_zip::base::read::seek::ZipFileReader` panicked with subtraction overflow.
This pull request provides a test which reproduces the error and the fix.
> Fix subtraction overflow for empty archives

- src/base/read/mod.rs
- src/base/write/entry_stream.rs
- src/base/write/entry_whole.rs
- src/base/write/mod.rs
- src/spec/extra_field.rs
- src/spec/header.rs
- src/tests/write/zip64/mod.rs
This is a very small PR that fixes https://github.com/Majored/rs-async-zip/issues/105 .
If the cumulative file size of all zip entrys exceeds the 4 Gib maximum for standard Zip a Zip64 EOCDR & EOCDL is needed.
This was not set automatically if no single entry exceeded the limit, the PR fixes this by checking the `force_no_zip64` flag and updating the `is_zip64` boolean if its allowed, otherwise the `LargeFile` error is raised:
```rust
if cd_offset > NON_ZIP64_MAX_SIZE as u64 {
if self.force_no_zip64 {
return Err(crate::error::ZipError::Zip64Needed(crate::error::Zip64ErrorCase::LargeFile));
} else {
self.is_zip64 = true;
}
}
```
Afterwards the correct EOCDR & EOCDL for Zip64 will be added.
#105 revealed an additional problem with Zip64 handling:
Zip64 is needed in one of the following …
> Small fix for missing Zip64 EOCDR / EOCDL if cumulative size > 4Gib and all entrys are < 4Gib

- src/base/read/mod.rs
- src/base/write/entry_stream.rs
- src/spec/extra_field.rs
- src/spec/parse.rs
This PR fixes an issue with parsing the Zip64 extended information field. See the linked issue for more details. 
In the future, it may make sense to restructure the extra field parsing to provide header context (e.g. uncompressed size, compressed size, etc) in a cleaner way, but this seemed to be the simplest change to fix this issue.
Fixes #108 
Tested locally with large zip files that failed without this change.
> Fix a bug in zip64 parsing

- src/base/read/mod.rs
- src/entry/mod.rs
- tests/decompress_test.rs
when I partly download a zip file, I has know the compress  format ,and I only want the compressed file part from the whole file.
I can use the 
file_offset+header_size 
to get the file part start. also seems the #113  has the same need , so I make this pr.
I found the failed test is test_read_zip64_archive_mem
the reason is because the `zip64.zip` file 's 
Central directory structure and the Local File Header
it has different value about the Extra field length
so it does not support all zip64 extra.
Shoud I maybe add the header_size on the `ZipEntry` ,not the `StoredZipEntry` ?
> add entry header size

- src/base/write/entry_stream.rs
- src/base/write/entry_whole.rs
- src/base/write/io/offset.rs
- src/base/write/mod.rs
- src/spec/extra_field.rs
- src/spec/header.rs
Hello!
This PR fixes problems with usize on 32bit systems(WASM)
Also it fixes problems with local header offset in zip64 archives that are more than 4 gb size.
> Fix for 32bit platforms. Fix for large zip64 archives.

- src/tests/write/mod.rs
This trivial patch was originally written by @decathorpe for Fedora’s [`rust-async_zip`](https://src.fedoraproject.org/rpms/rust-async_zip) package, but I don’t think we ever got around to offering it upstream.
Without this, on 32-bit platforms, `cargo test` fails like:
```
error[E0080]: attempt to compute `42950_usize * 100000_usize`, which would overflow
--> src/tests/write/zip64/mod.rs:17:34
|
17 | const BATCHED_FILE_SIZE: usize = NUM_BATCHES * BATCH_SIZE;
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `tests::write::zip64::BATCHED_FILE_SIZE` failed here
note: erroneous constant encountered
--> src/tests/write/zip64/mod.rs:17:34
|
17 | const BATCHED_FILE_SIZE: usize = NUM_BATCHES * BATCH_SIZE;
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^
note: …
```
> Compile and run large-file tests only on 64-bit architectures
